services:
###> doctrine/doctrine-bundle ###
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
      - "8444:443"
    volumes:
      - ./:/var/www/html:ro,cached
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - symfony
    networks:
      - symfony

  symfony:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/html:cached
      - ./infra/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./infra/php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
    networks:
      - symfony

  database:
    image: mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql:delegated
    networks:
      - symfony

   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
    ports:
      - "8083:80"
    depends_on:
      - database
    networks:
      - symfony
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  symfony:
    name: symfony
